# Generated by Django 5.1.4 on 2025-01-19 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_order_cartitems'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='cartItems',
        ),
    ]
