# Generated by Django 5.1.4 on 2025-01-19 09:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
        ('orders', '0008_remove_order_cartitems'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cartItems',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='items', to='cart.cartitems'),
            preserve_default=False,
        ),
    ]
