# Generated by Django 5.1.4 on 2025-01-19 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_alter_order_cartitems'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='cartItems',
        ),
    ]
