# Generated by Django 5.1.4 on 2025-01-19 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
        ('orders', '0012_remove_order_cartitems'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cart_items',
            field=models.ManyToManyField(related_name='orders', to='cart.cartitems'),
        ),
    ]
