# Generated by Django 5.1.4 on 2025-01-28 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0017_order_razorpay_order_id_order_razorpay_payment_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='razorpay_payment_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='razorpay_signature',
        ),
    ]
